export enum AudiSteps {
  SCOPE_EVALUATION = 'SCOPE_EVALUATION',
  FUNCTION_EVALUATION = 'FUNCTION_EVALUATION',
  REPORTING = 'REPORTING',
  COMPLETED = 'COMPLETED'
}

export enum OverallAuditStatus {
  PENDING_ANALYST_SCOPE_REVIEW = 'PENDING_ANALYST_SCOPE_REVIEW',
  PENDING_MANAGER_SCOPE_INPUT = 'PENDING_MANAGER_SCOPE_INPUT',
  PENDING_ANALYST_ANSWER_REVIEW = 'PENDING_ANALYST_ANSWER_REVIEW',
  PENDING_MANAGER_ANSWER_REVIEW = 'PENDING_MANAGER_ANSWER_REVIEW',
  PENDING_MANAGER_ANSWER_INPUT = 'PENDING_MANAGER_ANSWER_INPUT',
  PENDING_ANALYST_REPORT = 'PENDING_ANALYST_REPORT',
  FINALIZED = 'FINALIZED'
}
