export enum AudiSteps {
  SCOPE_EVALUATION = 'SCOPE_EVALUATION',
  FUNCTION_EVALUATION = 'FUNCTION_EVALUATION',
  REPORTING = 'REPORTING',
  COMPLETED = 'COMPLETED'
}

export enum ScopeFormActions {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  NEEDS_REVISION = 'NEEDS_REVISION',
  APPROVED = 'APPROVED'
}

export enum OverallAuditStatus {
  PENDING_ANALYST_SCOPE_REVIEW = 'PENDING_ANALYST_SCOPE_REVIEW',
  PENDING_MANAGER_SCOPE_INPUT = 'PENDING_MANAGER_SCOPE_INPUT',
  PENDING_ANALYST_ANSWER_REVIEW = 'PENDING_ANALYST_ANSWER_REVIEW',
  PENDING_MANAGER_ANSWER_REVIEW = 'PENDING_MANAGER_ANSWER_REVIEW',
  PENDING_MANAGER_ANSWER_INPUT = 'PENDING_MANAGER_ANSWER_INPUT',
  PENDING_ANALYST_REPORT = 'PENDING_ANALYST_REPORT',
  FINALIZED = 'FINALIZED'
}

export enum AuditFunction {
  ALCANCE_FUNCIONAL_GOBERNAR = 'alcance_funcional_gobernar',
  ALCANCE_FUNCIONAL_IDENTIFICAR = 'alcance_funcional_identificar',
  ALCANCE_FUNCIONAL_PROTEGER = 'alcance_funcional_proteger',
  ALCANCE_FUNCIONAL_DETECTAR = 'alcance_funcional_detectar',
  ALCANCE_FUNCIONAL_RESPONDER = 'alcance_funcional_responder',
  ALCANCE_FUNCIONAL_RECUPERAR = 'alcance_funcional_recuperar'
}
