name: CI/CD Pipeline

on:
  # Trigger on pushes to dev and prod branches
  push:
    branches:
      - dev
      - prod
      - staging

env:
  IMAGE_NAME: web_ui

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: 📦 Build Docker Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: 🔑 Log in to registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Tag and Push Docker Image
        run: |
          IMAGE_ID=ghcr.io/${{github.repository_owner}}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          if [[ "$BRANCH_NAME" == "prod" ]]; then
            TAG="prod"
          elif [[ "$BRANCH_NAME" == "staging" ]]; then
            TAG="staging"
          else
            TAG="latest"
          fi
          
          echo IMAGE_ID=$IMAGE_ID
          echo TAG=$TAG
          docker tag $IMAGE_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG
