name: test-and-build

on:
  pull_request:
    branches:
      - prod
      - staging
      - dev

env:
  IMAGE_NAME: web_ui

jobs:
  test-and-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 📦 Build dev Docker Image
        run: docker build --target dev -t ${IMAGE_NAME}:dev .

      - name: 📦 Build prod Docker Image
        run: docker build --target prod -t ${IMAGE_NAME}:prod .

      - name: ✅ Run Unit Tests in dev Docker Container
        run: docker run ${IMAGE_NAME}:dev npm run test:unit:ci
